name = "satelite"
license = "GPL-3.0"
licenselink = "https://github.com/LKummer/Satelite/blob/master/LICENSE.md"
description = "Create beautiful documentation websites"
homepage = "https://lkummer.github.io/Satelite"
tags = ["Documentation", "Wiki"]
features = ["Search", "SEO", "Color Customization", "Responsive"]
min_version = "0.81.0"

[author]
  name = "Lior Kummer"
  homepage = "https://github.com/LKummer"
