name = "satelite"
license = "GPL-3.0"
licenselink = ""
description = ""
homepage = "https://lkummer.github.io/Satelite"
tags = []
features = []
min_version = "0.81.0"

[author]
  name = "Lior Kummer"
  homepage = "https://github.com/LKummer"
