baseURL = ""
title = "Satelite"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "satelite"
pygmentsUseClasses = true

taxonomies = []

[outputs]
  home = ["HTML", "JSON"]

[menu]
[[menu.main]]
  name = "Github"
  url = "https://github.com/LKummer/Satelite"

[params]
[params.seo]
  description = "Satelite Hugo theme documentation."
[params.colors]
  primary-b1 = "hsl(355, 5%, 98%)"
  primary-b2 = "hsl(355, 5%, 97.5%)"
  primary-b3 = "hsl(355, 5%, 95%)"
  primary-b4 = "hsl(355, 7.5%, 96%)"
  primary-b5 = "hsl(355, 5%, 94%)"
  primary-a1 = "hsl(355, 20%, 90%)"
  primary-a2 = "hsl(350, 50%, 50%)"
  primary-a3 = "hsl(350, 60%, 40%)"
  primary-a4 = "hsl(350, 70%, 35%)"
  primary-f4 = "hsl(355, 20%, 45%)"
  primary-f5 = "hsl(355, 5%, 40%)"
  primary-f6 = "hsl(355, 25%, 30%)"
  primary-f7 = "hsl(355, 35%, 25%)"
  secondary-b2 = "hsl(355, 5%, 97.5%)"
  secondary-b3 = "hsl(355, 95%, 30%)"
  secondary-b4 = "hsl(350, 95%, 28%)"
  secondary-b5 = """
  linear-gradient(
    30deg,
    hsl(0, 80%, 20%),
    hsl(350, 90%, 25%))"""
  secondary-a1 = "hsl(355, 20%, 90%)"
  secondary-f1 = "hsl(350, 15%, 80%)"
  secondary-f9 = "hsl(350, 5%, 50%)"
  tertiary-b5 = "hsl(350, 2.5%, 95%)"
  tertiary-b6 = "hsl(350, 30%, 90%)"
  tertiary-b7 = "hsl(350, 35%, 88%)"
  tertiary-a3 = "hsl(350, 35%, 70%)"
  tertiary-f3 = "hsl(350, 20%, 45%)"
  tertiary-f4 = "hsl(350, 50%, 50%)"
  tertiary-f5 = "hsl(350, 60%, 50%)"
  tertiary-f6 = "hsl(350, 50%, 50%)"
[params.icons]
  favicon = "images/favicon.svg"
  navbarIcon = """
    <svg class="navbar-logo-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
      viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
      <style type="text/css">
        .logo-satelite {
          fill: hsl(350, 50%, 85%);
          transform-origin: 32px 32px;
          transform: rotate(calc(var(--logo-hover) * 360deg));
          transition: transform 1s;
        }
        .logo-planet {
          fill: hsl(350, 50%, 85%);
        }
        .logo-planet-shade {
          fill: hsl(350, 40%, 70%);
        }
      </style>
      <path class="logo-satelite" d="M59.8,21.6c-0.1,0.1-0.2,0.1-0.3,0.2c-0.3,0.2-0.5,0.3-0.8,0.4c-1.8,0.6-3.9-0.2-4.9-1.9
        c-1-1.7-0.6-3.9,0.8-5.2C46,3.9,30.2,0.6,17.6,7.9C5,15.1,0,30.4,5.3,43.5c0.5,1.2,1.1,2.5,1.8,3.7c0.2,0.3,0.1,0.6-0.2,0.8
        c-0.3,0.2-0.6,0.1-0.8-0.2c-0.7-1.2-1.3-2.5-1.8-3.8C-1.3,30.4,3.9,14.4,17,6.8s29.6-4.1,38.6,7.5c2-1,4.3-0.2,5.5,1.7
        C62.2,17.9,61.6,20.3,59.8,21.6z"/>
      <circle class="logo-planet" cx="32" cy="32.8" r="20.4"/>
      <path class="logo-planet-shade" d="M52.4,32.8c0,11.3-9.1,20.4-20.4,20.4c-3.5,0-6.7-0.9-9.5-2.4c-1.5-2.8-2.4-6.1-2.4-9.5
        c0-11.3,9.1-20.4,20.4-20.4c3.4,0,6.7,0.9,9.5,2.4C51.5,26.1,52.4,29.3,52.4,32.8z"/>
    </svg>
    """
